### ISSUE TITLE
Launch error for SmitherZ on latest fabric loader, with required mods.

### ISSUE THREAD

**Issue by Karthsteel** [Globox1997/SmitherZ#1]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.24

### Mod Version

1.0.0 (early preview dated 18/11/2023)

### Describe the Issue

I have installed the early preview of SmitherZ and added its dependencies (which is AARP, autotag, cloth config, fabric api, and libz, based on what I could gather), and have attempted to launch an instance of 1.20.1 with said mod. Upon attempting to launch, I get the error described in the gist I have provided.

### latest.log

https://gist.github.com/Karthsteel/690bfb74fbfc1571cb61452257d4b359

### Do you use any other mods except the required ones?

I did try it with EMI so I could look at the items bundled with smitherz, but that didn't change anything.

**Comment by Globox1997** [comment]
Thanks for the report, fixed with [https://github.com/Globox1997/SmitherZ/commit/8ef0575ff916edf3e845d0752ed853f21b18d947](https://github.com/Globox1997/SmitherZ/commit/8ef0575ff916edf3e845d0752ed853f21b18d947)
