### ISSUE TITLE
Iceberg Crash?

### ISSUE THREAD

**Issue by KevzCz** [Globox1997/SmitherZ#2]
### Minecraft Version

1.20.x

### Mod Loader Version

1.50.1

### Mod Version

1.0.0

### Describe the Issue

Install iceberg + Legendary Tool Tips+ Smitherz and all its dependencies, crash upon hovering over a Smitherz item ( I did crash upon start-up but only sometimes )

### latest.log

- Crash Report
https://gist.github.com/KevzCz/b6810437477ffa49ba659edcadd8ed95
- Latest Log
https://gist.github.com/KevzCz/88f600797b5fbd1a5a721d7e797a74c0

### Do you use any other mods except the required ones?

Yes but i've tested it on a different instance with the mods described in the issue

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/SmitherZ/commit/ca15ea0c3b9d15701ac0d82aa5ebcd5c25ed6bfa](https://github.com/Globox1997/SmitherZ/commit/ca15ea0c3b9d15701ac0d82aa5ebcd5c25ed6bfa)
