### ISSUE TITLE
Gems working and Not working

### ISSUE THREAD

**Issue by qxZap** [Globox1997/SmitherZ#3]
### Minecraft Version

1.20.x

### Mod Loader Version

0.14.25

### Mod Version

1.0.2

### Describe the Issue

While keeping

### latest.log

Some gems don't grant any effect when equipped 
![image](https://github.com/Globox1997/SmitherZ/assets/22640856/3f3a8361-4ef4-4e0f-a19d-c3ee3b4f30c4)
Yet when holding the item with the gem inside in hand the effect is granted
![image](https://github.com/Globox1997/SmitherZ/assets/22640856/ef34d345-a211-4c15-94c9-fe66815c223c)
Also. Some gems can't even go on may armors from various mods. I suspect this is because of tags

Also, if you keep the gems in hand you will get the effects anyway. Don't think that is intended

### Do you use any other mods except the required ones?

Yes. Many but nothing that affects smitherz directly

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/SmitherZ/commit/0fae6608cf6a8c1541719f980fbae2c86731ebea](https://github.com/Globox1997/SmitherZ/commit/0fae6608cf6a8c1541719f980fbae2c86731ebea)
