### ISSUE TITLE
Gem bonuses only applying when held in hand and not working well worn

### ISSUE THREAD

**Issue by cole3050** [Globox1997/SmitherZ#4]
### Minecraft Version

1.20.x

### Mod Loader Version

fabric 0.15.7

### Mod Version

1.0.2

### Describe the Issue

Gem bonuses only apply when held, this includes gems equipped to Armor. 

### latest.log

nil

### Do you use any other mods except the required ones?

TieredZ and LevelZ were the only mods used outside the required ones for my recent test

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/SmitherZ/commit/0fae6608cf6a8c1541719f980fbae2c86731ebea](https://github.com/Globox1997/SmitherZ/commit/0fae6608cf6a8c1541719f980fbae2c86731ebea)
